#!/bin/bash

function update_version_in_changelog() {
  version=$1
  file=wiki/Changelog.wiki
  svn up $file >/dev/null 2>&1
  sed -i "s/\(\*Latest Safari version\*:\) *\([0-9.]\+\)/\1 $version/" $file
  echo
  svn diff $file
  echo
  echo -n "Updating Safari latest version in Changelog.  Does this look right (y/n)? "
  read answer
  [ "$answer" = y ] && {
    echo svn ci $file -m "Update Safari latest version in Changelog to $version"
  }
}

sdir=safaribuild_tempdir.safariextension
cd $(dirname $0)
cd ..
dir=$(basename $(pwd))
cd ..

v=$(grep -A 1 'CFBundleVersion' $dir/Info.plist | tail -1 | cut -d '>' -f 2 | cut -d '<' -f 1)
vd=$(grep -A 1 'CFBundleShortVersionString' $dir/Info.plist | tail -1 | cut -d '>' -f 2 | cut -d '<' -f 1)
[ "10$vd" = "$v" ] || {
  echo "Bundle version in Info.plist isn't 100 + display version."
  exit 1
}
echo -n "You expect to ship version $v (displayed as $vd), right? (y/n) "
read answer
[ "$answer" = y ] || exit 1

rm -rf $sdir
cp -R $dir $sdir
rm -rf $sdir/tools/
find $sdir -name .svn | xargs rm -rf
clear
echo Load $sdir into Safari and build safaribuild.safariextz.
echo Save it in $(pwd)/.
echo
echo Press enter when done.
read

[ -f safaribuild_tempdir.safariextz ] || {
  echo "safaribuild_tempdir.safariextz needs to be in $(pwd)."
  exit 1
}

echo -n "Type your username: "
read user
ssh="ssh $user@safariadblock.com"

rdir="webapps/mg_safariadblock_com"
$ssh "[ -d $rdir/versions/$vd ]" && {
  echo "Sorry, version $vd already exists on the server."
  exit 1
}

$ssh "mkdir $rdir/versions/$vd"

scp safaribuild_tempdir.safariextz $user@safariadblock.com:$rdir/versions/$vd/AdBlockForSafari.safariextz || {
  echo "Failed to scp"
  exit 1
}

rm -rf safaribuild_tempdir.safariext*

$ssh "$rdir/point_to_version $vd"

update_version_in_changelog $vd

echo "Last step: update update.plist on the server to notify users."
